version: 2
updates:
  # master branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    commit-message:
      prefix: "ci"
      include: "scope"
  # development branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "ci"
      include: "scope"
