version: 2
updates:
  # main branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "ci"
      include: "scope"
  # 0.1.x branch (old master)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "0.1.x"
    commit-message:
      prefix: "ci"
      include: "scope"
