minimum_pre_commit_version: 4.0.0
default_install_hook_types: [pre-commit, commit-msg]
ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: end-of-file-fixer
        name: check for missing newline at the end of files
        stages: [pre-commit]
      - id: mixed-line-ending
        name: check for mixed line endings
        stages: [pre-commit]
      - id: name-tests-test
        name: check for correct naming of Python tests
        stages: [pre-commit]
        args: ["--pytest-test-first"]
      - id: trailing-whitespace
        stages: [pre-commit]

  # C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 182152eb8c5ce1cf5299b956b04392c86bd8a126  # frozen: v20.1.8
    hooks:
      - id: clang-format
        name: format C++ files with clang-format
        stages: [pre-commit]
        types: [c++]

  # CMake
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: e2c2116d86a80e72e7146a06e68b7c228afc6319  # frozen: v0.6.13
    hooks:
    - id: cmake-format
      name: check formatting of CMake files
      stages: [pre-commit]
      additional_dependencies: [pyyaml>=5.1]
    - id: cmake-lint
      name: lint CMake files
      stages: [pre-commit]
      additional_dependencies: [pyyaml>=5.1]

  # Python
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: 79cc0ae5abfa1ba092b5938cd811a6069710ad77  # frozen: v2.8.0
    hooks:
      - id: setup-cfg-fmt
        name: check formatting of setup.cfg
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 13a6bda8ea7612b3aec844ded16569d424b9a1ab  # frozen: v0.13.0
    hooks:
      - id: ruff
        name: check Python files with ruff
        stages: [pre-commit]
      - id: ruff-format
        name: format Python files with ruff
        stages: [pre-commit]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 8184a5b72f4a8fcd003b041ecb04c41a9f34fd2b  # frozen: v2.6.0
    hooks:
      - id: pyproject-fmt
        name: check formatting of pyproject.toml
        stages: [pre-commit]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 0bc601e0cc771b26b206a46d3b298ef951b43c7c  # frozen: 1.19.1
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==25.1.0

  # CI
  - repo: https://github.com/rhysd/actionlint
    rev: 03d0035246f3e81f36aed592ffb4bebf33a03106  # frozen: v1.7.7
    hooks:
      - id: actionlint
        name: check GitHub workflow files
        stages: [pre-commit]

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: dacb08719019f4b28c462aba22b35c82db22e17c  # frozen: 41.113.7
    hooks:
      - id: renovate-config-validator
        args: [--strict]

  # docs
  - repo: https://github.com/executablebooks/mdformat
    rev: 83dc2ce5ca115d3390b9b5561d2898366faf0742  # frozen: 0.7.22
    hooks:
      - id: mdformat
        name: check formatting of Markdown files
        stages: [pre-commit]
        additional_dependencies:
          - mdformat-tables

  # spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac  # frozen: v2.4.1
    hooks:
      - id: codespell
        name: check for common spelling errors
        stages: [pre-commit]

  # commit messages
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: 7bc85936608ba0ae03887bb6e110555535d1c3ac  # frozen: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        name: check commit messages for conventional format
        stages: [commit-msg]
        args:
          - --types=fix,feat,build,chore,ci,docs,perf,refactor,revert,style,test,improvement
