name: CI build Linux

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu 24.04 - GCC 9.5.0",
            cc: "gcc-9", cxx: "g++-9"
          }
        - {
            name: "Ubuntu 24.04 - GCC 10.5.0",
            cc: "gcc-10", cxx: "g++-10"
          }
        - {
            name: "Ubuntu 24.04 - GCC 11.4.0",
            cc: "gcc-11", cxx: "g++-11"
          }
        - {
            name: "Ubuntu 24.04 - GCC 12.3.0",
            cc: "gcc-12", cxx: "g++-12"
          }
        - {
            name: "Ubuntu 24.04 - Clang 14.0.6",
            cc: "clang-14", cxx: "clang++-14"
          }
        - {
            name: "Ubuntu 24.04 - Clang 15.0.7",
            cc: "clang-15", cxx: "clang++-15"
          }

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install ${{ matrix.config.cxx }} || sudo apt install ${{ matrix.config.cc }}
          sudo apt install libeigen3-dev

      - name: Configure
        run: |
          cmake \
            -Bbuild \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
