name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: pre-commit
    uses: ./.github/workflows/pre-commit.yaml

  linting:
    name: Linting
    uses: ./.github/workflows/style.yaml

  cpp:
    name: C++ build and test
    needs: [linting]
    uses: ./.github/workflows/cpp.yaml

  python:
    name: Python build and test
    needs: [cpp]
    uses: ./.github/workflows/python.yaml

  static_analysis:
    name: Static analysis
    needs: [linting]
    uses: ./.github/workflows/sonarcloud.yaml
    secrets: inherit

  benchmarks:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    name: Benchmarks
    needs: [cpp, python]
    uses: ./.github/workflows/benchmarks.yaml
    secrets: inherit

  conclusion:
    name: Conclusion
    if: always()
    needs:
      - pre-commit
      - linting
      - cpp
      - python
      - static_analysis
      - benchmarks
    runs-on: ubuntu-24.04
    steps:
      - name: Exit on failure
        if: >-
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled') ||
          (needs.benchmarks.result == 'failure')
        run: |
          echo "❌ Some required jobs failed"
          exit 1

      - name: Success message
        run: |
          echo "✅ All required jobs completed successfully"
