name: C++ code coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Codecov
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - name: Dependencies
        run: |
          sudo apt install libeigen3-dev
          python -m pip install gcovr

      - name: Configure
        run: |
          cmake \
            -Bbuild \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=clang-16 \
            -DCMAKE_CXX_COMPILER=clang++-16 \
            -DOVERLAP_WITH_COVERAGE=ON

      - name: Build
        run: cmake --build build

      - name: Generate coverage report
        run: |
          cd build
          ctest --output-on-failure
          ~/.local/bin/gcovr \
            --gcov-executable 'llvm-cov-16 gcov' \
            --exclude-lines-by-pattern '.*overlap_assert.*' \
            -r ../ \
            --xml -o coverage.xml \
            -e ../third_party/ -e ../tests/src

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: ./build/coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
