name: C++ build and test 🐧

on:
  workflow_call:

jobs:
  build:
    name: "${{ matrix.config.name }} [${{ matrix.build_type }}]"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # GCC on x86-64
          - { name: "GCC 9.5.0", os: "ubuntu-22.04", cc: "gcc-9", cxx: "g++-9" }
          - {
              name: "GCC 10.5.0",
              os: "ubuntu-22.04",
              cc: "gcc-10",
              cxx: "g++-10",
            }
          - {
              name: "GCC 11.4.0",
              os: "ubuntu-22.04",
              cc: "gcc-11",
              cxx: "g++-11",
            }
          - {
              name: "GCC 12.3.0",
              os: "ubuntu-22.04",
              cc: "gcc-12",
              cxx: "g++-12",
            }
          - {
              name: "GCC 13.2.0",
              os: "ubuntu-24.04",
              cc: "gcc-13",
              cxx: "g++-13",
            }
          - {
              name: "GCC 14.0.1",
              os: "ubuntu-24.04",
              cc: "gcc-14",
              cxx: "g++-14",
            }
          # GCC on arm64
          - {
              name: "GCC 12.3.0 (AArch64)",
              os: "ubuntu-22.04-arm",
              cc: "gcc-12",
              cxx: "g++-12",
            }
          - {
              name: "GCC 14.0.1 (AArch64)",
              os: "ubuntu-24.04-arm",
              cc: "gcc-14",
              cxx: "g++-14",
            }
          # LLVM/Clang on x86-64
          - {
              name: "Clang 11.1.0",
              os: "ubuntu-22.04",
              cc: "clang-11",
              cxx: "clang++-11",
            }
          - {
              name: "Clang 12.0.1",
              os: "ubuntu-22.04",
              cc: "clang-12",
              cxx: "clang++-12",
            }
          - {
              name: "Clang 13.0.1",
              os: "ubuntu-22.04",
              cc: "clang-13",
              cxx: "clang++-13",
            }
          - {
              name: "Clang 14.0.0",
              os: "ubuntu-22.04",
              cc: "clang-14",
              cxx: "clang++-14",
            }
          - {
              name: "Clang 15.0.7",
              os: "ubuntu-22.04",
              cc: "clang-15",
              cxx: "clang++-15",
            }
          - {
              name: "Clang 16.0.6",
              os: "ubuntu-24.04",
              cc: "clang-16",
              cxx: "clang++-16",
            }
          - {
              name: "Clang 17.0.6",
              os: "ubuntu-24.04",
              cc: "clang-17",
              cxx: "clang++-17",
            }
          - {
              name: "Clang 18.1.3",
              os: "ubuntu-24.04",
              cc: "clang-18",
              cxx: "clang++-18",
            }
          # LLVM/Clang on arm64
          - {
              name: "Clang 15.0.7 (AArch64)",
              os: "ubuntu-22.04-arm",
              cc: "clang-15",
              cxx: "clang++-15",
            }
          - {
              name: "Clang 18.1.3 (AArch64)",
              os: "ubuntu-24.04-arm",
              cc: "clang-18",
              cxx: "clang++-18",
            }
          # LLVM/Clang on macOS/arm64 using libc++
          - {
              name: "Clang 15.0.0 (macOS, AArch64)",
              os: "macos-14",
              cc: "clang",
              cxx: "clang++",
            }

        build_type: ["Debug", "Release"]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true

      - name: Dependencies
        if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install ${{ matrix.config.cxx }} || sudo apt install ${{ matrix.config.cc }}
          sudo apt install libeigen3-dev

      - name: Configure
        run: |
          cmake \
            -Bbuild \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
