name: Python build and test 🐧

on:
  workflow_call:

jobs:
  build:
    name: "🐍 Ubuntu 24.04 ${{ endsWith(matrix.os, 'arm') && 'AArch64' || 'x86-64' }} - Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Dependencies
        run: |
          sudo apt install libeigen3-dev
          uv sync --no-build --frozen --all-extras --dev --no-install-project

      - name: Install project
        run: uv sync --frozen --all-extras --dev

      - name: Run tests
        run: uv run --frozen pytest -vs
