name: Convert pre-commit tags to hashes

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".pre-commit-config.yaml"

jobs:
  convert-tags:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install requests

      - name: Convert tags to hashes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/scripts/convert-precommit-tags.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .pre-commit-config.yaml
            git commit -m "chore: convert pre-commit tags to commit hashes for security"
            git push
          fi
